### ISSUE TITLE
Use file_handle_cache

### ISSUE THREAD

**Issue by michaelklishin** [cloudamqp/msg_store_eleveldb_index#2]
This extension should use RabbitMQ's `file_handle_cache` to make sure it accounts for all the descriptor its OS processes actually opens.

Otherwise it may run out of file descriptors before an alarm has a chance to fire, which may lead to catastrophic consequences for the node.

**Comment by michaelklishin** [comment]
I'd be interested in contributing this, most likely after 3.5.0 ships. We would like to recommend this extension but without this change, cannot do that.

**Comment by carlhoerberg** [comment]
Does that mean that we have to modify eleveldb to use `file_handle_cache` instead of `file` everywhere?

**Comment by michaelklishin** [comment]
We can notify FHC from this module right after operations that we know result in open file handles. That is unlikely to be always possible.

**Comment by michaelklishin** [comment]
After investigating this a bit I come to the conclusion that we can't even use `obtain/0` and `release/0` from FHC. LMS tree-like data stores manage files as black boxes.

[HanoidDB](https://github.com/krestenkrab/hanoidb/blob/master/DESIGN.md) looks a lot more predictable than most. We'll investigate it and consider recommending this plugin with a warning.

**Comment by michaelklishin** [comment]
After doing some research I come to the conclusion that indeed hooking into FHC would not be possible even with a fork of `eleveldb` (which I by no means consider to be a good idea).

I think we should make it very clear in the docs that this message index's use of file descriptors will not be accounted for by the FHC and additional file descriptors should be allowed (e.g. `10000` to be on the safe side).
